apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: chat-saas
build:
  artifacts:
  - image: quay.io/hown3d/chat-api-server
    docker:
      dockerfile: Dockerfile
  local:
    useBuildkit: true
    #custom:
    #  buildCommand: |
    #    CGO_ENABLED=0 go build -o _output/server ./cmd/server/main.go 
    #    DOCKER_BUILDKIT=1 docker build --tag=$IMAGE --build-arg BUILD_ENV=builder-binary .
      # dependencies:
      #   dockerfile:
      #     path: Dockerfile
      #     buildArgs:
      #       BUILD_ENV: builder-binary

    # docker:
    #   dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment/devel.yaml

# profiles:
#   - name: debug
#     build:
#       artifacts:
#       - image: hown3d/chat-api-server
#         docker:
#           dockerfile: Dockerfile
#           target: builder
#       local:
#         useBuildkit: true
#   - name: prod
#     build:
#       artifacts:
#       - image: hown3d/chat-api-server
#         docker:
#           dockerfile: Dockerfile
#           target: prod
#       local:
#         useBuildkit: true